### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by ayseff** [Yitzchok/Zmanim#2]
@Yitzchok, are you looking for contributors?

**Comment by Yitzchok** [comment]
Yes if you are interested please fork this project and make your changes and submit a pull request.

**Comment by ayseff** [comment]
What needs work? I saw you mentioned something about making objects
LINQable...Do you have any specifics?

**Comment by Yitzchok** [comment]
The HebrewCalendar part wasn't finished

This should probably be implemented so that it uses the .NET calendar which supports the conversion of Gregorian dates to Hebrew dates.

Once that is done we can get the Daf Yomi calculator to work and the Jewish Calendar (Holidays and Parshiyot) implemented


https://github.com/Yitzchok/Zmanim/tree/master/src/Zmanim/HebrewCalendar
