### ISSUE TITLE
Month Index for JewishDate.cs when setting via DateTime

### ISSUE THREAD

**Issue by dakom** [Yitzchok/Zmanim#9]
I believe the index might be off by 1 when setting JewishDate via DateTime. In other words, given a DateTime which corresponds to Iyar, passing it to JewishDate will cause the month settings for the JewishDate object to be Sivan instead

Relevant code:
`gregorianMonth = value.Month + 1`
- [line 1017 on JewishDate.cs](https://github.com/Yitzchok/Zmanim/blob/3903d6815e82713009c0fdb8c42d0aae144fdc89/src/Zmanim/HebrewCalendar/JewishDate.cs#L1017)

Proposed fix is to change the line to:

`gregorianMonth = value.Month`

References showing that the index from DateTime is 1-based (as opposed to 0-based): 

> The month component, expressed as a value between 1 and 12.
- [DateTime.Month reference](https://msdn.microsoft.com/en-us/library/system.datetime.month(v=vs.110).aspx)

> Tishrei = 1
- [HebrewCalendar ms reference](https://msdn.microsoft.com/en-us/library/system.globalization.hebrewcalendar(v=vs.110).aspx)

(note: I considered making a fork/pull request but noticed that you are in the midst of overhauling the JewishCalendar/Date stuff as it is due to GPL compliance issues, and figured this might be more efficient. Plus I'd rather you confirm that I am not mistaken before submitting a change ;))

**Comment by Yitzchok** [comment]
Hi dakom,

This is one of the reasons that I didn't include it in the project and I never got around to fixing it.

Also you have to take a leap year into account since the Tishrei is 1 and not Nissan (which I think is the case in Java)

Most of that class can go away since converting from the Gregorian calendar to the Hebrew Calander is part of the .NET framework which isn't the case for Java.


I would love to take a pull request if you get this to work the correct way.

**Comment by dakom** [comment]
OK, cool, I'm not great at C# but this seems like more generic stuff of
figuring out the way MS handles calendar dates etc.

Happy to work on it, over next week most likely... as it is, I've got some
code I'm using to translate GregorianCalendar<->HebrewCalendar and it seems
to be working fine (it's a little bit proprietary at the moment, hooked
into the UI and dropdowns and things, but I can try to separate that out
and contribute it toward your project if it helps)

Couple preliminary questions:

1) Do you have some tests setup somewhere, i.e. given Gregorian or Hebrew
dates XYZ we expect certain results from JewishCalendar.YomTovIndex etc?

2) I'm using this for a project I'm building for Jewish Interactive, and
while we/they are a non-profit, the app needs to be closed-source at the
end of the day. Ultimately this is fine for the LGPL stuff but I can't use
GPL... any suggestions of how I can contribute to JewishCalendar but under
the LGPL zmanim project? (don't need parsha necessarily, but I do need Yom
Tov and the other goodies)

I'm in Israel, so goodnight - and happy lag b'omer! :)

Thanks,
David

**Comment by Yitzchok** [comment]
.Net has built in GregorianCalendar<->HebrewCalendar you just have to figure out how it works.

From what I understand the complicated part of JewishCalendar is the parsha part since for jewish holidays you can make a simple mapping to a Hebrew Date aka 1 tishrai = rosh hashana, 2 tishrai = rosh hashana, 10 tishrai = yom kipur (fast days/purim that are pushed around are a little more complex)

**Comment by dakom** [comment]
Got it, forking under my employer's github organization and will hopefully
be able to help out during work time :D

**Comment by dakom** [comment]
Figured out how to run the tests.... and right off the bat a few failed :\

Do you use Gitter or have Slack open so we can talk a bit more easily? :)

**Comment by dakom** [comment]
FYI I've got a new JewishCalendar brewing based off of .NET rather than the numerical calculations... I stripped away the parsha stuff so it's only holiday also

Unfortunately it's currently failing a test to convert June 12, 2016 to Sivan... and I probably can't get back to it till Monday, but hopefully will fix it then. Just wanted to give a heads up. Good Shabbos!

https://github.com/jewish-interactive/Zmanim/blob/master/src/Zmanim/JewishCalendar/JewishCalendar.cs
